accounts/urls.py
from django.contrib import admin
from django.urls import include, path
from django.contrib.auth import views as auth_views
from django.urls import reverse_lazy

from . import views

urlpatterns = [

    path("login/", auth_views.LoginView.as_view(), name="login"),
    path("logout/", auth_views.LogoutView.as_view(next_page=reverse_lazy("forum:post_list")), name="logout"),
    path("register", views.register, name="register"),

    # https://docs.djangoproject.com/en/3.0/topics/auth/default/#using-the-views    
    path("", include("django.contrib.auth.urls")),
]

forum/urls.py
from django.urls import path

from . import views

app_name = "forum"

urlpatterns = [
    path("", views.PostListView.as_view(), name="post_list"),
    path("<int:pk>", views.PostDetailView.as_view(), name="post_detail"),
    path("post/create", views.PostCreateView.as_view(), name="post_create"),
    path("post/edit/<int:pk>", views.PostUpdateView.as_view(), name="post_edit"),
    path("post/delete/<int:pk>", views.PostDeleteView.as_view(), name="post_delete"),
]

workshop2/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("forum.urls")),
    path('accounts/', include('accounts.urls')),
]

accounts/models.py
from django.db import models

# Create your models here.

forum/models.py
from django.db import models

from django.utils import timezone
from django.contrib.auth.models import User

# Create your models here.

# class User(models.Model):
#     name = models.CharField(max_length=64, unique=True)

#     def __str__(self):
#         return f"{self.id} : {self.name}"


class Post(models.Model):
    active = models.BooleanField(default=True)
    content = models.TextField()
    picture_url = models.CharField(max_length=200, null=True)
    author = models.ForeignKey( User,
                                on_delete=models.SET_NULL,
                                null=True,
                                related_name="posts")

    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

forum/forms.py
from django.forms import ModelForm
from django.core.exceptions import ValidationError

from . import models

class PostForm(ModelForm):
    class Meta:
        model = models.Post
        exclude = ("active","author")

    # customize validation
    def clean_post(self):
        min_words = 5

        data = self.cleaned_data["post"]

        if (data.count(" ") + data.count("\n")) < min_words:
            raise ValidationError(f"Post should have more than {min_words} words.")

        return data

accounts/views.py
# Create your views here.
# templates suggestion:
#  https://github.com/macdhuibh/django-registration-templates

from django.contrib.auth.forms import UserCreationForm
from django.shortcuts import render, redirect

def register(request):
    if request.method == 'POST':
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()

            return redirect("/")
    else:
        form = UserCreationForm()
        
    return render(request, "registration/register.html", {'form': form})

forum/views.py
from django.shortcuts import redirect, get_object_or_404
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView, UpdateView 
from django.views import View
from django.urls import reverse_lazy
from django.contrib.auth.mixins import (
    LoginRequiredMixin, 
    UserPassesTestMixin,
    PermissionRequiredMixin,
)
from . import models, forms
from django.http import HttpResponseForbidden

#from django.http.response import HttpResponse
from django.http import HttpResponse
from django.shortcuts import render
from django.contrib.auth import models as auth_models
from django.http import HttpResponseForbidden


"""
    # for function based view:
    #
    #from django.contrib.auth.decorators import login_required
    #@login_required        
"""
"""
    # function based view
    from django.contrib.auth.decorators import permission_required

    @permission_required("forum.view_post")
    def permission_on_function_based_view(request):
        return render(request, "forum/post_list.html", {})
"""

def handle_403(request, exception):
    return HttpResponse("Permission denied (error 403)", status=403)

def handle_404(request, exception):
    return HttpResponse("Di ko makita ang page (error 404)", status=404)

#    response = render(request, "404.html", {})
#    response.status_code = 404
#    return response

class PostListView( ListView):
    model = models.Post
    fields = "__all__"
    queryset = models.Post.objects.filter(active=True).order_by("-date_updated")
    permission_required = ("forum.view_post",)

    #def get(self, request, *args, **kwargs):
    #    if not request.user.has_perm("forum.view_post"):
    #        return HttpResponseForbidden("You are not allowed to do that")
    #    
    #    return super().get(request, *args, **kwargs)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        context["user"] = self.request.user

        return context

class PostDetailView(DetailView):
    model = models.Post
    #queryset = models.Post.objects.filter(active=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.get_object().author == self.request.user or self.request.user.is_superuser:
            context["hide_button"] = False
        else :
            context["hide_button"] = True
        print(self.get_object().author, self.request.user, context)
        return context

class PostCreateView(CreateView):
    form_class = forms.PostForm
    template_name = "forum/post_form.html"
    success_url = reverse_lazy("forum:post_list")
    
    def _is_banned(self, request):
        status = request.user.groups.filter(name="Banned").exists()
        #status = request.user in auth_models.Group.objects.get(name="Banned").user_set.all()
        if status:
            return HttpResponseForbidden("You are currently banned in this social website.")

    def get(self, request, *args, **kwargs):
        status = self._is_banned(request)
        if status:
            return status

        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        status = self._is_banned(request)
        if status:
            return status
        
        instance = models.Post()
        form = self.form_class(request.POST, instance=instance)
        if form.is_valid():
            if request.user.is_authenticated:
                instance.author = request.user

            form.save()

            return redirect(self.success_url)
        
        return render(request, self.template_name, {"form": form})

class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    form_class = forms.PostForm
    queryset = models.Post.objects.all()
    success_url = reverse_lazy("forum:post_list")

    def test_func(self):
        return (
            self.get_object().author == self.request.user or
            self.request.user.is_superuser
        )

        #test1 = self.get_object().author == self.request.user
        #test2 = self.request.user.is_superuser
        #return any([test1, test2, test3, test4])

class PostDeleteView(View):

    def get(self, request, *args, **kwargs):

        testimonial = get_object_or_404(models.Post, id=kwargs["pk"])
        testimonial.active = False
        testimonial.save()

        return redirect("forum:post_list")

forum/templates/forum/post_detail.html
{% extends 'base.html' %}

{% block content%}

{% if object.active %}
    Name: {{ object.author | title }} <br />
    Time of posting: {{ object.created }} <br />
    {% if object.created != object.date_updated %}
        Last modified: {{ object.date_updated }} <br />
    {% endif %}
    <hr>
    {{ object.content }} <br />

    {% if object.picture_url %}
        <img src="{{ object.picture_url }}" alt="">
    {% endif %}


    {% if hide_button == False %}
        <a href="{% url "forum:post_edit" object.id %}">Edit</a>
        <a href="{% url "forum:post_delete" object.id %}">Delete</a>
    {% endif %}
{% else %}
    This content have been deleted.
{% endif %}

{% endblock %}

forum/templates/forum/post_form.html
{% extends 'base.html' %}

{% block content%}

<form method="post">
    {% csrf_token %}
    
    {{ form.as_p }}

    {% if form.instance.pk %}
        <input type="submit" value="Update" />
    {% else %}
        <input type="submit" value="Create post" />
    {% endif %}
</form>

{% endblock %}

forum/templates/forum/post_list.html
{% extends 'base.html' %}

{% block content%}

{% if not user.is_anonymous %}
    <div class = "menu">
        <h3>
            Welcome {{ user.username }}!
        </h3>
        <a class="create-post-a" href="{% url "forum:post_create" %}">Create Post</a>
    </div>
{% endif %}

{% for object in object_list %}
    <div class="list-card">
        <div class="list-card-img"
            style="background-image: url({{ object.picture_url }});"
        >
    
        </div>
        <div class="list-card-body">
            <div class ="list-card-header">
                <h3>
                    {{ object.author | title }}
                </h3> 
                <p>
                    Since: {{ object.date_updated }}
                </p>
            </div>
            <p>
                {{ object.content | truncatewords:3}}
            </p>
            <div class="list-card-footer">
                <a href="{% url "forum:post_detail" object.id %}">Read more</a>
            </div>
        </div>

    </div>
{% endfor %}

{% endblock %}

templates/base.html
{% load sass_tags %}
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ImageBook</title>
    <link href="{% sass_src 'main.scss' %}" rel="stylesheet" type="text/css" />
</head>
<body>
    
    <div class="top_nav">
        <div class = "middle_nav">
            <h3>
                <a class="logo" href="{% url "forum:post_list" %}">Imagebook</a>
            </h3>
            <div class = "options_nav">
                
                {% if not user.is_anonymous %}
                    <a href="{% url "logout" %}">Logout</a>
                {% else %}
                    <a href="{% url "login" %}">Login</a>
                    <a href="{% url "register" %}">Sign up</a>
                {% endif %}
            </div>  
        </div>
    </div>
    <section class="main-section">
        {% block content%}
        {% endblock %}
    </section>
    
</body>
</html>